version: '3.8'

services:
  node:
    image: node:20-alpine
    container_name: fullcycle-node
    command: sh -c "npm install && npm start"
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - "3000"
    depends_on:
      - db

  nginx:
    image: nginx:1.25.3-alpine
    container_name: fullcycle-nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node

  db:
    image: mysql:8.3
    container_name: fullcycle-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
      - ./bootstrap.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: fullcycle